version: "3"
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8000:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: node server.js
    restart: on-failure
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_USER
      MYSQL_ROOT_PASSWORD: $DB_PASS

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "7000:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
